# Site
repository: B-K05.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brian Knight
title: Student at Metro Tech
email: knightbrian005@gmail.com
website: B-K05.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username:
#github_username:
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: Brian Knight
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
- #title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Brian and I have experience with working on computers and their parts. I work well with people and I am excited when faced with new challenges. 

  I am most skilled in: <mark>Computer Repair</mark> and <mark>Computer Construction</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Device Configuration and Management
        link: https://gmetrix.net/Dashboard.aspx/Program/384
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This was an online course taken while at my current place of education.
        description: | # this will include new lines to allow paragraphs
          In a nutshell, this course introduces basic and some complicated computer concepts such as Task Manager, BIOS setup, Operating systems and their repective capabilities, etc.

  - title: Current Attendance # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Metro Tech
        link: https://www.metrotech.edu/about/locations/springlake-campus
        # link_text: boringcompany.com
        sub_title: Student
        caption: August 2024 - Present
        quote: >
          Currently attending Metro Tech at their campus in Sprinkglake and enrolled in the Cybersecurity & Networking course
        description: | # this will include new lines to allow paragraphs
            The course I'm enrolled in takes a hands-on approach to teaching us concepts about computer and network management, as well as coding languages such as python.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Southeast Highschool
        caption: 2020 - 2024
        sub_title:
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Southeast Highschool is a technology-based application school that offers multiple tech-based subjects such as computer science and fundamentals of technology

          During my time at Southeast, I helped set up, photograph, and record multiple school events such as photographing for the school yearbook and journal, recoring and editing interviews, and I worked on multiple plays that the school had put on by helping set up and recording the full things

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computers and hardware, some of my other interests and hobbies are:
      - Weightlifting
      - Gaming
      - Fishing
      - Music

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
